// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimerParcial.Data;

namespace Restaurantee.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201201035712_add-plato-detalle")]
    partial class addplatodetalle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Restaurantee.Models.clasificacionIngredientes", b =>
                {
                    b.Property<int>("idClasificacionIngredientes")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tipoClientes");

                    b.HasKey("idClasificacionIngredientes");

                    b.ToTable("clasificacionIngredientes");
                });

            modelBuilder.Entity("Restaurantee.Models.inventario", b =>
                {
                    b.Property<int>("idInventario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantidad");

                    b.Property<int>("idClasificacionIngredientes");

                    b.Property<string>("ingrediente");

                    b.HasKey("idInventario");

                    b.HasIndex("idClasificacionIngredientes");

                    b.ToTable("inventarios");
                });

            modelBuilder.Entity("Restaurantee.Models.mesa", b =>
                {
                    b.Property<int>("idMesa")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion");

                    b.Property<string>("estado");

                    b.Property<int>("numeroMaximoDePersonas");

                    b.Property<string>("ubicacion");

                    b.HasKey("idMesa");

                    b.ToTable("mesas");
                });

            modelBuilder.Entity("Restaurantee.Models.pedido", b =>
                {
                    b.Property<int>("idPedido")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("fechaPedido");

                    b.Property<int>("idMesa");

                    b.Property<int>("idPlato");

                    b.Property<decimal>("impuesto");

                    b.Property<string>("observaciones")
                        .IsRequired();

                    b.Property<string>("persona")
                        .IsRequired();

                    b.Property<int?>("platoidPlatos");

                    b.Property<decimal>("subTotal");

                    b.Property<decimal>("total");

                    b.HasKey("idPedido");

                    b.HasIndex("idMesa");

                    b.HasIndex("platoidPlatos");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("Restaurantee.Models.pedidoDetalle", b =>
                {
                    b.Property<int>("idPedidoDetalle")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantidad");

                    b.Property<int>("idPedido");

                    b.Property<int>("idPlato");

                    b.Property<decimal>("impuesto");

                    b.Property<int?>("platoidPlatos");

                    b.Property<decimal>("precio");

                    b.Property<decimal>("subTotal");

                    b.Property<decimal>("total");

                    b.HasKey("idPedidoDetalle");

                    b.HasIndex("idPedido");

                    b.HasIndex("platoidPlatos");

                    b.ToTable("pedidoDetalles");
                });

            modelBuilder.Entity("Restaurantee.Models.plato", b =>
                {
                    b.Property<int>("idPlatos")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad");

                    b.Property<string>("Nombre");

                    b.Property<int>("Precio");

                    b.HasKey("idPlatos");

                    b.ToTable("plato");
                });

            modelBuilder.Entity("Restaurantee.Models.usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido");

                    b.Property<string>("clave")
                        .IsRequired();

                    b.Property<string>("direccion");

                    b.Property<string>("nombre")
                        .IsRequired();

                    b.Property<string>("role");

                    b.Property<string>("telefono");

                    b.HasKey("idUsuario");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("Restaurantee.Models.inventario", b =>
                {
                    b.HasOne("Restaurantee.Models.clasificacionIngredientes", "clasificacion")
                        .WithMany()
                        .HasForeignKey("idClasificacionIngredientes")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Restaurantee.Models.pedido", b =>
                {
                    b.HasOne("Restaurantee.Models.mesa", "mesa")
                        .WithMany()
                        .HasForeignKey("idMesa")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Restaurantee.Models.plato", "plato")
                        .WithMany()
                        .HasForeignKey("platoidPlatos");
                });

            modelBuilder.Entity("Restaurantee.Models.pedidoDetalle", b =>
                {
                    b.HasOne("Restaurantee.Models.pedido", "pedido")
                        .WithMany()
                        .HasForeignKey("idPedido")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Restaurantee.Models.plato", "plato")
                        .WithMany()
                        .HasForeignKey("platoidPlatos");
                });
#pragma warning restore 612, 618
        }
    }
}
